config/routes.rb
Rails.application.routes.draw do
   devise_for :users, controllers: {
        sessions: 'users/sessions',
        registrations: 'users/registrations'
      }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "home#index" 
  resources :books do
    member do
      post 'rent'
    end
  end
  resources :rentals, only: [:index, :show] do
    member do
      put 'return'
    end
  end
  get 'rented_books', to: 'rentals#admin_index', as: 'rented_books' 
end

app/models/book.rb
class Book < ApplicationRecord
	has_many :rentals, dependent: :destroy
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authorize_admin!, only: [:new, :create]

  def index
    @books = Book.page(params[:page]).per(10)
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])

    if @book.update(book_params)
      redirect_to @book, notice: 'Book was successfully updated.'
    else
      flash.now[:alert] = 'Failed to update the book.'
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    if @book.destroy
      redirect_to books_url, notice: 'Book was successfully deleted.'
    else
      Rails.logger.error("Failed to delete the book: #{@book.errors.full_messages}")
      flash[:alert] = 'Failed to delete the book.'
      redirect_back(fallback_location: books_url)
    end
  end

  def create
    @book = Book.new(book_params)
    @book.available_quantity = @book.total_quantity

    if @book.save
      redirect_to @book, notice: 'Book was successfully added.'
    else
      flash.now[:alert] = 'Failed to add the book.'
      render :new
    end
  end

  def rent
    @book = Book.find(params[:id])
    if @book.available_quantity > 0
      Rental.create(user: current_user, book: @book, due_date: 7.days.from_now)
      @book.decrement!(:available_quantity)
      redirect_to @book, notice: 'Book rented successfully.'
    else
      redirect_to @book, alert: 'Sorry, the book is not available for rental.'
    end
  end

  private

  def book_params
    params.require(:book).permit(:title, :author, :total_quantity, :price)
  end

  def authorize_admin!
    redirect_to root_path, alert: 'You are not authorized to perform this action.' unless current_user&.admin?
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>XYZ Book Rental - Edit Book</title>
  <%= stylesheet_link_tag 'style' %>
</head>
<body>
  <div class="edit-book-container">
    <h1>Edit Book</h1>

    <%= form_with(model: @book, local: true) do |form| %>
      <div>
        <%= form.label :title %>
        <%= form.text_field :title %>
      </div>

      <div>
        <%= form.label :author %>
        <%= form.text_field :author %>
      </div>

      <div>
        <%= form.label :total_quantity %>
        <%= form.number_field :total_quantity %>
      </div>

      <div>
        <%= form.label :price %>
        <%= form.number_field :price %>
      </div>

      <div>
        <%= form.submit 'Update' %>
      </div>
    <% end %>

  </div>
</body>
</html>

app/views/books/index.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>XYZ Book Rental - Sign Up</title>
  <%= stylesheet_link_tag 'book' %>
</head>

<body>
<div class="container mt-5 margin-top-navbar">
  <h1 class="mb-4">Book List</h1>
  <%= paginate @books %>

  <div class="row">
    <% @books.each do |book| %>
      <div class="col-md-4 mb-4">
        <div class="card h-100">
          <div class="card-body">
            <h2 class="card-title"><%= link_to book.title, book, class: 'text-decoration-none text-dark' %></h2>
            <p class="card-text"><strong>Author:</strong> <%= book.author %></p>
            <p class="card-text"><strong>Status:</strong> <%= book.available_quantity.present? && book.available_quantity.positive? ? 'Available' : 'Not Available' %></p>
            <p class="card-text"><strong>Price:</strong> <%= book.price %></p>

            <% if user_signed_in? && !current_user.admin? && book.available_quantity.present? && book.available_quantity.positive? %>
            <%= link_to 'Rent', rent_book_path(book), method: :post, data: { confirm: 'Are you sure?' }, class: 'btn btn-primary btn-sm' %>
            <% end %>

            <% if user_signed_in? && current_user.admin? %>
              <%= link_to 'Edit', edit_book_path(book), class: 'btn btn-warning btn-sm' %>
              <%= link_to 'Delete', book, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
</body>

</html>

app/views/books/new.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>XYZ Book Rental - Sign Up</title>
  <%= stylesheet_link_tag 'style' %>
</head>

<body>
<div class="new-book-container">
  <h1>New Book</h1>

  <%= form_with(model: @book, local: true) do |form| %>
    <div>
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>

    <div>
      <%= form.label :author %>
      <%= form.text_field :author %>
    </div>

    <div>
      <%= form.label :total_quantity %>
      <%= form.number_field :total_quantity %>
    </div>

    <div>
      <%= form.label :price %>
      <%= form.number_field :price %>
    </div>

    <div>
      <%= form.submit 'Add Book' %>
    </div>
  <% end %>
</div>
</body>

</html>

app/views/books/show.html.erb
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>XYZ Book Rental - Sign Up</title>
  <%= stylesheet_link_tag 'style' %>
  <style>
    .new-book-container {
      margin: 20px;
      display: flex;
    }

    .book-details {
      flex: 1;
      margin-right: 20px;
    }

    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 20px;
    }

    th, td {
      border: 1px solid #dddddd;
      text-align: left;
      padding: 8px;
    }

    th {
      background-color: #f2f2f2;
    }
  </style>
</head>

<body>
  <div class="new-book-container">
    <div class="book-details">
      <h1><%= @book.title %></h1>

      <table>
        <tbody>
          <tr>
            <th>Author</th>
            <td><%= @book.author %></td>
          </tr>
          <tr>
            <th>Total Quantity</th>
            <td><%= @book.total_quantity %></td>
          </tr>
          <tr>
            <th>Available Quantity</th>
            <td><%= @book.available_quantity || 0 %></td>
          </tr>
          <tr>
            <th>Price</th>
            <td><%= @book.price%></td>
          </tr>
        </tbody>
      </table>

      <% if user_signed_in? %>
        <% if @book.available_quantity.to_i > 0 && !current_user.rented?(@book) %>
          <%= link_to 'Rent', rent_book_path(@book), method: :post, data: { confirm: 'Are you sure?' }, class: 'btn btn-primary' %>
        <% end %>
      <% end %>
    </div>

    <div class="borrowed-by">
      <h2>Borrowed By:</h2>
      <table>
        <thead>
          <tr>
            <th>User</th>
            <th>Due Date</th>
          </tr>
        </thead>
        <tbody>
          <% @book.rentals.each do |rental| %>
            <tr>
              <td><strong>User:</strong> <%= rental.user.firstname %></td>
              <% if rental.due_date.present? %>
                <td><strong>Due Date:</strong> <%= rental.due_date.strftime('%B %d, %Y') %></td>
              <% else %>
                <td><strong>Due Date:</strong> Not available</td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</body>

</html>